var imgHero = {
	image1:["DESIGN THAT INSPIRES THE SAME AS THE DRIVE.","MAZDA MX-5 MIATA"],
	image2:["NAMED A CAR AND DRIVER \"10BEST\" THREE YEARS IN A ROW","THE 2016 MAZDA3 4-DOOR"],
	image3:["PERFORMANCE, EFFICIENCY, EXCITEMENT.","THE 2016 MAZDA6 WITH SKYACTIV\u00ae TECHNOLOGY"],
	image4:["INDULGE EVERY SENSE. INCLUDING COMMON SENSE.","THE ALL-NEW 2016 MAZDA CX-9"],
	image5:["CONFIDENT DRIVING IS BETTER DRIVING.","THE 2016 MAZDA CX-5"]
	};